[theme]
base = "dark"
primaryColor = "#3b82f6"
backgroundColor = "#191919"
secondaryBackgroundColor = "#202024"
textColor = "#ececec"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
