[theme]
base = "dark"
primaryColor = "#0a84ff"
backgroundColor = "#0f0f11"
secondaryBackgroundColor = "#1a1a1e"
textColor = "#f2f2f4"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
